version: 0.1.{build}
os: Ubuntu
configuration: Debug
platform: Any CPU
install:
- curl -L https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-linux.tar.gz -o premake.tar.gz
- tar zxf premake.tar.gz
- ./premake5 gmake2
build_script:
- git submodule init
- git submodule update
- make
test_script:
  - sh: |
      ./bin/64bit/Debug/experimental-tests -r junit -o experimental-tests.64.debug.xml
      err=$?
      curl -F 'file=@experimental-tests.64.debug.xml' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
      exit $err
artifacts:
  - path: experimental-tests.64.debug.xml
    name: Log File
